"""Reusable HTML components for Industrial Chrome Aesthetic reports."""

from typing import List, Dict, Optional


# =============================
# 🎨 CSS STYLES
# =============================

def get_industrial_chrome_css() -> str:
    """Complete CSS for industrial chrome metallic design matching Waymo report theme."""
    return """
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Roboto:wght@400;600;700;900&display=swap');

        /* ============================================
           RESET & BASE STYLES
           ============================================ */
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'Roboto', sans-serif;
            background: linear-gradient(135deg, #1e293b 0%, #334155 100%);
            padding: 10px 20px;
            min-height: 100vh;
        }

        /* Wrapper container for reports generated by Python */
        .report-container {
            max-width: 1900px;
            margin: 0 auto;
        }

        /* ============================================
           NAVIGATION BUTTONS (Top Chrome Buttons)
           ============================================ */
        .nav-container {
            display: flex;
            gap: 12px;
            margin-bottom: 30px;
            flex-wrap: wrap;
        }

        .nav-button {
            flex: 1;  /* ← ADDED: Makes buttons equal width */
            min-width: 150px;  /* ← ADDED: Minimum button width */
            background: linear-gradient(145deg, #808080 0%, #606060 100%);
            color: white;
            border: 2px solid;
            border-color: #60a5fa #505050 #505050 #60a5fa;
            border-radius: 12px;
            padding: 14px 20px;  /* ← INCREASE HEIGHT*/
            font-weight: 700;
            font-size: 0.85em;
            cursor: pointer;
            transition: all 0.3s ease;
            box-shadow: 
                inset 0 1px 0 rgba(255,255,255,0.3),
                inset 0 -1px 0 rgba(0,0,0,0.2),
                0 3px 0 #505050,
                0 5px 10px rgba(59,130,246,0.5);
            text-shadow: 0 1px 2px rgba(0,0,0,0.4);
            text-decoration: none;
            display: inline-block;
            text-align: center;
        }

        .nav-button:hover {
            transform: translateY(-2px);
            box-shadow: 
                inset 0 1px 0 rgba(255,255,255,0.4),
                inset 0 -1px 0 rgba(0,0,0,0.25),
                0 4px 0 #505050,
                0 7px 15px rgba(59,130,246,0.6);
        }

        .nav-button:active {
            transform: translateY(1px);
            box-shadow: 
                inset 0 1px 0 rgba(255,255,255,0.3),
                inset 0 -1px 0 rgba(0,0,0,0.2),
                0 1px 0 #505050,
                0 3px 6px rgba(59,130,246,0.4);
        }

        .nav-button.active {
            background: linear-gradient(145deg, #3b82f6 0%, #2563eb 100%);
            border-color: #93c5fd #1f2937 #1f2937 #93c5fd;
        }

        /* ============================================
           CHROME INDUSTRIAL HEADER
           ============================================ */
        .header {
            background: 
                linear-gradient(135deg, 
                    rgba(255,255,255,0.1) 0%, 
                    transparent 20%, 
                    transparent 80%, 
                    rgba(0,0,0,0.2) 100%),
                linear-gradient(135deg, 
                    #000814 0%, 
                    #505050 25%, 
                    #808080 50%, 
                    #505050 75%, 
                    #000814 100%);
            padding: 15px 20px;
            text-align: center;
            border-radius: 16px;
            margin-bottom: 30px;
            position: relative;
            overflow: hidden;
            border: 3px solid;
            border-color: #60a5fa #505050 #505050 #60a5fa;
            box-shadow: 
                inset 0 2px 0 rgba(255,255,255,0.2),
                inset 0 -2px 0 rgba(0,0,0,0.4),
                0 8px 0 #505050,
                0 10px 0 #505050,
                0 12px 0 #1e293b,
                0 16px 30px rgba(0,0,0,0.6);
        }

        .header::before {
            content: '';
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            height: 60%;
            background: linear-gradient(180deg, 
                rgba(255,255,255,0.25) 0%,
                rgba(255,255,255,0.1) 30%, 
                transparent 100%);
        }

        .header-title {
            font-size: 2.2em;
            font-weight: 900;
            text-transform: uppercase;
            letter-spacing: 2px;
            color: white;
            text-shadow: 
                0 1px 0 rgba(255,255,255,0.3),
                0 2px 4px rgba(0,0,0,0.8),
                0 4px 8px rgba(0,0,0,0.6);
            margin-bottom: 10px;
            position: relative;
            z-index: 1;
        }

        .header-subtitle {
            font-size: 1.1em;
            color: #bfdbfe;
            font-weight: 600;
            position: relative;
            z-index: 1;
            text-shadow: 0 1px 3px rgba(0,0,0,0.6);
        }

        .header-meta-line {
            font-size: 1em;
            color: #e5e7eb;
            margin-top: 4px;
            text-shadow: 0 1px 2px rgba(0,0,0,0.6);
        }

        /* ============================================
           METADATA GRID  (mimic .report-meta / .meta-item)
           ============================================ */
        .metadata-grid {
            margin-top: 20px;
            margin-bottom: 20px;
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
            gap: 10px;
        }

        .metadata-card {
            text-align: center;
            padding: 15px;
            background: linear-gradient(145deg, #ffffff 0%, #f0f0f0 100%);
            border-radius: 8px;
            border: 1px solid;
            border-color: rgba(255,255,255,0.8) rgba(0,0,0,0.1) rgba(0,0,0,0.1) rgba(255,255,255,0.8);
            box-shadow: 
                inset 0 1px 0 rgba(255,255,255,0.8),
                0 2px 4px rgba(0,0,0,0.1);
        }

        .metadata-icon {
            font-size: 1.4em;
            margin-bottom: 6px;
        }

        .metadata-label {
            font-size: 0.85em;
            color: #6b7280;
            text-transform: uppercase;
            letter-spacing: 1px;
            margin-bottom: 8px;
            font-weight: 700;
            text-shadow: 0 1px 0 rgba(255,255,255,0.8);
        }

        .metadata-value {
            font-size: 1.4em;
            font-weight: 800;
            color: #505050;
            text-shadow: 
                0 1px 0 rgba(255,255,255,0.8),
                0 2px 3px rgba(0,0,0,0.2);
        }

        /* Conditional coloring for OT Exposure card */
        .metadata-card.ot-critical {
            border: 2px solid #dc2626;
            background: linear-gradient(145deg, #fee2e2 0%, #fecaca 100%);
        }

        .metadata-card.ot-critical .metadata-label {
            color: #991b1b;
        }

        .metadata-card.ot-critical .metadata-value {
            color: #dc2626;
        }

        .metadata-card.ot-warning {
            border: 2px solid #f59e0b;
            background: linear-gradient(145deg, #fef3c7 0%, #fde68a 100%);
        }

        .metadata-card.ot-warning .metadata-label {
            color: #78350f;
        }

        .metadata-card.ot-warning .metadata-value {
            color: #d97706;
        }

        .metadata-card.ot-good {
            border: 2px solid #059669;
            background: linear-gradient(145deg, #dcfce7 0%, #bbf7d0 100%);
        }

        .metadata-card.ot-good .metadata-label {
            color: #065f46;
        }

        .metadata-card.ot-good .metadata-value {
            color: #059669;
        }

        /* ============================================
           SECTIONS (Beveled Chrome Containers)
           ============================================ */
        .section {
            background: linear-gradient(145deg, #f8f9fa 0%, #e9ecef 100%);
            border-radius: 16px;
            margin-bottom: 25px;
            border: 3px solid;
            border-color: #ffffff #c0c0c0 #a0a0a0 #ffffff;
            box-shadow: 
                inset 0 2px 0 rgba(255,255,255,0.9),
                inset 0 -2px 0 rgba(0,0,0,0.2),
                0 6px 0 #c0c0c0,
                0 8px 0 #a0a0a0,
                0 10px 20px rgba(0,0,0,0.4);
            overflow: hidden;
            transition: all 0.3s ease;
        }

        .section-header {
            background: 
                linear-gradient(145deg, 
                    rgba(255,255,255,0.08) 0%, 
                    transparent 20%, 
                    transparent 80%, 
                    rgba(0,0,0,0.15) 100%),
                linear-gradient(135deg, 
                    #1f2937 0%, 
                    #374151 50%, 
                    #1f2937 100%);
            padding: 20px 30px;
            cursor: pointer;
            display: flex;
            align-items: center;
            gap: 12px;
            position: relative;
            border-bottom: 3px solid;
            border-image: linear-gradient(90deg, 
                #3b82f6 0%, 
                #60a5fa 50%, 
                transparent 100%) 1;
            box-shadow: 
                inset 0 2px 0 rgba(255,255,255,0.1),
                inset 0 -2px 0 rgba(0,0,0,0.3),
                0 4px 8px rgba(0,0,0,0.2);
            transition: all 0.3s ease;
        }

        .section-header:hover {
            background: 
                linear-gradient(145deg, 
                    rgba(255,255,255,0.12) 0%, 
                    transparent 20%, 
                    transparent 80%, 
                    rgba(0,0,0,0.18) 100%),
                linear-gradient(135deg, 
                    #374151 0%, 
                    #4b5563 50%, 
                    #374151 100%);
            box-shadow: 
                inset 0 2px 0 rgba(255,255,255,0.15),
                inset 0 -2px 0 rgba(0,0,0,0.35),
                0 6px 12px rgba(0,0,0,0.25);
        }

        .section-toggle {
            font-size: 1.1em;
            font-weight: 900;
            color: #60a5fa;
            text-shadow: 0 2px 4px rgba(0,0,0,0.4);
            transition: transform 0.3s ease;
        }

        .section.expanded .section-toggle {
            transform: rotate(90deg);
        }

        .section-title {
            font-size: 1.3em;
            font-weight: 800;
            color: white;
            text-transform: uppercase;
            letter-spacing: 1.5px;
            text-shadow: 
                1px 1px 0 rgba(0,0,0,0.4),
                2px 2px 4px rgba(0,0,0,0.5);
            flex: 1;
        }

        .section-content {
            max-height: 0;
            overflow: hidden;
            transition: max-height 0.5s ease-out;
            background: white;
        }

        .section.expanded .section-content {
            max-height: 50000px;
            transition: max-height 1s ease-in;
        }

        .section-inner {
            padding: 30px;
        }

        /* ============================================
           PRIORITY TITLE (Chrome Warning Banner)
           ============================================ */
        .priority-title-container {
            text-align: center;
            margin-bottom: 30px;
            position: relative;
        }

        .priority-title {
            display: inline-flex;
            align-items: center;
            justify-content: center;
            gap: 15px;
            margin: 0 auto;
        }

        .priority-title {
            font-size: 1.5em;
            font-weight: 900;
            text-transform: uppercase;
            letter-spacing: 3px;
            background: linear-gradient(180deg, 
                #ffffff 0%,
                #fef3c7 30%,
                #fde68a 50%,
                #fef3c7 70%,
                #ffffff 100%);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            background-clip: text;
            filter: drop-shadow(0 2px 4px rgba(0,0,0,0.8))
                    drop-shadow(0 0 10px rgba(254,243,199,0.5));
        }

        .priority-icon,
        .warning-icon {
            font-size: 1.8em;
            animation: iconFlash 1.5s ease-in-out infinite;
            filter: drop-shadow(0 0 8px rgba(251,191,36,0.8));
        }

        @keyframes iconFlash {
            0%, 100% { opacity: 1; transform: scale(1); }
            50% { opacity: 0.6; transform: scale(1.1); }
        }

        /* ============================================
           SITE CARDS GRID (map to Waymo nav cards)
           ============================================ */
        .site-cards-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));
            gap: 20px;
            margin: 0 auto 20px auto;
            max-width: 1600px;
        }

        .site-card {
            background: linear-gradient(145deg, #ffffff 0%, #f0f0f0 100%);
            border-radius: 12px;
            padding: 15px;
            cursor: pointer;
            transition: all 0.3s ease;
            border: 2px solid;
            box-shadow: 
                inset 0 1px 0 rgba(255,255,255,0.8),
                0 3px 6px rgba(0,0,0,0.15);
        }

        .site-card.critical {
            border-color: #dc2626;
        }

        .site-card.warning {
            border-color: #f59e0b;
        }

        .site-card.good {
            border-color: #059669;
        }

        .site-card:hover {
            transform: translateY(-4px);
            box-shadow: 
                inset 0 1px 0 rgba(255,255,255,0.9),
                0 6px 12px rgba(0,0,0,0.25);
        }

        .site-card-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 10px;
        }

        .site-rank-badge {
            background: linear-gradient(145deg, #374151 0%, #1f2937 100%);
            color: white;
            font-size: 0.75em;
            font-weight: 800;
            padding: 4px 10px;
            border-radius: 6px;
            text-transform: uppercase;
            letter-spacing: 0.5px;
            text-shadow: 0 1px 2px rgba(0,0,0,0.5);
            box-shadow: 0 2px 4px rgba(0,0,0,0.2);
        }

        .site-number {
            font-size: 0.9em;
            font-weight: 800;
            color: #6b7280;
        }

        .site-location {
            font-size: 1.1em;
            font-weight: 800;
            color: #1f2937;
            margin-bottom: 12px;
            text-shadow: 0 1px 2px rgba(0,0,0,0.1);
        }

        .site-stats {
            margin-bottom: 12px;
            padding: 10px;
            background: linear-gradient(145deg, #f3f4f6 0%, #e5e7eb 100%);
            border-radius: 8px;
            text-align: center;
        }

        .stat-item {
            margin-bottom: 4px;
        }

        .stat-label {
            font-size: 0.75em;
            color: #6b7280;
            text-transform: uppercase;
            font-weight: 700;
            letter-spacing: 0.5px;
        }

        .stat-value {
            font-size: 1.1em;
            font-weight: 800;
            color: #1f2937;
        }

        .site-card-button {
            text-align: center;
            padding: 8px;
            background: linear-gradient(145deg, #dbeafe 0%, #bfdbfe 100%);
            border-radius: 6px;
            color: #1e40af;
            font-weight: 800;
            font-size: 0.85em;
            text-transform: uppercase;
            letter-spacing: 0.5px;
            border: 1px solid #93c5fd;
            transition: all 0.3s ease;
        }

        .site-card:hover .site-card-button {
            background: linear-gradient(145deg, #3b82f6 0%, #2563eb 100%);
            color: white;
            border-color: #1e40af;
            transform: translateY(-1px);
        }

        /* ============================================
           TABLES (Chrome / bevel style)
           ============================================ */
        .table-container {
            margin: 24px 0;
            overflow-x: auto;
        }

        .table-controls {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 15px;
            gap: 15px;
            flex-wrap: wrap;
        }

        .search-box {
            flex: 1;
            min-width: 250px;
            padding: 10px 15px;
            border: 2px solid #d1d5db;
            border-radius: 8px;
            font-size: 0.9em;
            background: white;
            box-shadow: inset 0 2px 4px rgba(0,0,0,0.06);
            transition: all 0.3s ease;
        }

        .search-box:focus {
            outline: none;
            border-color: #60a5fa;
            box-shadow: 
                inset 0 2px 4px rgba(0,0,0,0.06),
                0 0 0 3px rgba(59, 130, 246, 0.1);
        }

        .export-btn {
            background: linear-gradient(145deg, #3b82f6 0%, #2563eb 100%);
            color: white;
            border: none;
            padding: 10px 20px;
            border-radius: 8px;
            font-weight: 700;
            font-size: 0.85em;
            cursor: pointer;
            transition: all 0.3s ease;
            box-shadow: 
                0 2px 0 #1e40af,
                0 4px 8px rgba(37, 99, 235, 0.3);
        }

        .export-btn:hover {
            transform: translateY(-2px);
            box-shadow: 
                0 4px 0 #1e40af,
                0 6px 12px rgba(37, 99, 235, 0.4);
        }

        .export-btn:active {
            transform: translateY(0);
            box-shadow: 
                0 1px 0 #1e40af,
                0 2px 4px rgba(37, 99, 235, 0.3);
        }

        table {
            width: 100%;
            border-collapse: separate;
            border-spacing: 0;
            margin: 20px 0;
            background: white;
            border-radius: 8px;
            overflow: hidden;
            box-shadow: 
                0 2px 0 #c0c0c0,
                0 4px 0 #a0a0a0,
                0 6px 12px rgba(0,0,0,0.15);
        }

        thead {
            background: 
                linear-gradient(135deg, 
                    rgba(255,255,255,0.05) 0%, 
                    transparent 50%, 
                    rgba(0,0,0,0.1) 100%),
                linear-gradient(135deg, 
                    #374151 0%, 
                    #4b5563 50%, 
                    #374151 100%);
            box-shadow: 
                inset 0 2px 0 rgba(255,255,255,0.15),
                inset 0 -2px 0 rgba(0,0,0,0.3);
        }

        th {
            padding: 15px 20px;
            text-align: left;
            font-weight: 800;
            color: white;
            text-transform: uppercase;
            font-size: 0.85em;
            letter-spacing: 1px;
            border-right: 1px solid rgba(255,255,255,0.1);
            text-shadow: 0 1px 2px rgba(0,0,0,0.5);
            cursor: pointer;
            user-select: none;
            position: relative;
        }

        th:hover {
            background: rgba(59, 130, 246, 0.2);
        }

        th::after {
            content: ' ⇅';
            color: #60a5fa;
            opacity: 0.5;
            font-size: 0.75em;
        }

        th:last-child {
            border-right: none;
        }

        tbody tr {
            transition: all 0.2s ease;
            border-bottom: 1px solid #e5e7eb;
        }

        tbody tr:nth-child(even) {
            background: #f9fafb;
        }

        tbody tr:hover {
            background: linear-gradient(90deg, 
                rgba(59, 130, 246, 0.08) 0%, 
                rgba(59, 130, 246, 0.04) 100%);
            box-shadow: inset 0 0 0 1px rgba(59, 130, 246, 0.2);
        }

        tbody tr:last-child {
            border-bottom: none;
        }

        td {
            padding: 12px 20px;
            color: #1f2937;
            font-size: 0.95em;
            border-right: 1px solid #f3f4f6;
        }

        td:last-child {
            border-right: none;
        }

        td[style*="text-align: right"],
        td[style*="text-align:right"] {
            font-weight: 800;
            font-variant-numeric: tabular-nums;
        }

        td[style*="text-align: center"],
        td[style*="text-align:center"] {
            font-weight: 700;
        }

        /* ============================================
           STATUS BADGES
           ============================================ */
        .status-badge {
            display: inline-block;
            padding: 4px 10px;
            border-radius: 6px;
            font-size: 0.8em;
            font-weight: 800;
            text-transform: uppercase;
            letter-spacing: 0.5px;
            box-shadow: 
                inset 0 1px 0 rgba(255,255,255,0.3),
                0 2px 4px rgba(0,0,0,0.2);
            text-shadow: 0 1px 1px rgba(0,0,0,0.2);
        }

        .badge-green {
            background: linear-gradient(145deg, #10b981 0%, #059669 100%);
            color: white;
            border: 1px solid #047857;
        }

        .badge-yellow {
            background: linear-gradient(145deg, #fbbf24 0%, #f59e0b 100%);
            color: #78350f;
            border: 1px solid #d97706;
        }

        .badge-red {
            background: linear-gradient(145deg, #ef4444 0%, #dc2626 100%);
            color: white;
            border: 1px solid #b91c1c;
        }

        .badge-blue {
            background: linear-gradient(145deg, #60a5fa 0%, #3b82f6 100%);
            color: white;
            border: 1px solid #1d4ed8;
        }

        /* ============================================
           SITE SUBSECTIONS (Collapsible details)
           ============================================ */
        .site-subsection {
            margin: 0 0 20px 0;
            border-radius: 12px;
            overflow: hidden;
            background: linear-gradient(145deg, #ffffff 0%, #f9fafb 100%);
            border: 2px solid #e5e7eb;
            box-shadow: 0 2px 6px rgba(0,0,0,0.08);
        }

        .subsection-header {
            background: linear-gradient(145deg, #f3f4f6 0%, #e5e7eb 100%);
            padding: 15px 20px;
            cursor: pointer;
            display: flex;
            justify-content: space-between;
            align-items: center;
            border-bottom: 2px solid #d1d5db;
            transition: all 0.3s ease;
        }

        .subsection-header:hover {
            background: linear-gradient(145deg, #e5e7eb 0%, #d1d5db 100%);
        }

        .subsection-title {
            display: flex;
            align-items: center;
            gap: 12px;
            font-size: 1.1em;
            font-weight: 800;
            color: #1f2937;
        }

        .subsection-toggle {
            color: #3b82f6;
            font-size: 0.9em;
            font-weight: 900;
            transition: transform 0.3s ease;
        }

        .site-subsection.expanded .subsection-toggle {
            transform: rotate(90deg);
        }

        .quick-stats {
            display: flex;
            gap: 10px;
            align-items: center;
        }

        .quick-stat-pill {
            padding: 6px 12px;
            border-radius: 6px;
            font-size: 0.85em;
            font-weight: 800;
        }

        .quick-stat-pill.critical {
            background: linear-gradient(145deg, #fee2e2 0%, #fecaca 100%);
            color: #991b1b;
            border: 1px solid #f87171;
        }

        .quick-stat-pill.warning {
            background: linear-gradient(145deg, #fef3c7 0%, #fde68a 100%);
            color: #78350f;
            border: 1px solid #fbbf24;
        }

        .quick-stat-pill.good {
            background: linear-gradient(145deg, #dcfce7 0%, #bbf7d0 100%);
            color: #065f46;
            border: 1px solid #22c55e;
        }

        .subsection-content {
            max-height: 0;
            overflow: hidden;
            transition: max-height 0.5s ease-out;
        }

        .site-subsection.expanded .subsection-content {
            max-height: 10000px;
            transition: max-height 1s ease-in;
        }

        .subsection-inner {
            padding: 24px;
        }

        /* ============================================
           CONTEXT CARDS
           ============================================ */
        .context-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
            gap: 15px;
            margin: 20px 0;
        }

        .context-card {
            background: linear-gradient(145deg, #f9fafb 0%, #f3f4f6 100%);
            padding: 12px 15px;
            border-radius: 8px;
            border: 1px solid #e5e7eb;
            box-shadow: 
                inset 0 1px 0 rgba(255,255,255,0.9),
                0 2px 4px rgba(0,0,0,0.05);
        }

        .context-card.critical-card {
            background: linear-gradient(145deg, #fee2e2 0%, #fecaca 100%);
            border-color: #f87171;
        }

        .context-card.warning-card {
            background: linear-gradient(145deg, #fef3c7 0%, #fde68a 100%);
            border-color: #fbbf24;
        }

        .context-label {
            font-size: 0.75em;
            color: #6b7280;
            text-transform: uppercase;
            font-weight: 700;
            letter-spacing: 0.5px;
            margin-bottom: 5px;
        }

        .context-value {
            font-size: 1.1em;
            font-weight: 800;
            color: #1f2937;
        }

        .critical-card .context-value {
            color: #dc2626;
        }

        .warning-card .context-value {
            color: #d97706;
        }

        /* ============================================
           ACTION ITEMS
           ============================================ */
        .actions-container {
            margin-bottom: 24px;
        }

        .action-item {
            display: flex;
            gap: 15px;
            padding: 15px;
            margin: 10px 0;
            border-radius: 8px;
            border-left: 4px solid;
            box-shadow: 0 2px 4px rgba(0,0,0,0.08);
        }

        .action-item.action-critical {
            background: linear-gradient(145deg, #fee2e2 0%, #fecaca 100%);
            border-left-color: #dc2626;
        }

        .action-item.action-warning {
            background: linear-gradient(145deg, #fef3c7 0%, #fde68a 100%);
            border-left-color: #f59e0b;
        }

        .action-item.action-info {
            background: linear-gradient(145deg, #dbeafe 0%, #bfdbfe 100%);
            border-left-color: #3b82f6;
        }

        .action-icon {
            font-size: 1.8em;
            line-height: 1;
        }

        .action-content {
            flex: 1;
        }

        .action-title {
            font-size: 1em;
            font-weight: 800;
            color: #1f2937;
            margin-bottom: 5px;
        }

        .action-description,
        .action-desc {
            font-size: 0.9em;
            color: #4b5563;
            margin-bottom: 5px;
        }

        .action-details,
        .action-affected {
            font-size: 0.85em;
            color: #6b7280;
            font-style: italic;
        }

        /* ============================================
           INFO BOXES
           ============================================ */
        .info-box {
            background: linear-gradient(145deg, #eff6ff 0%, #dbeafe 100%);
            border-left: 4px solid #3b82f6;
            padding: 15px 20px;
            margin: 20px 0;
            border-radius: 8px;
            box-shadow: 0 2px 6px rgba(59, 130, 246, 0.1);
        }

        .info-box-title {
            color: #1e40af;
            font-size: 0.9em;
            font-weight: 900;
            margin-bottom: 6px;
            text-transform: uppercase;
            letter-spacing: 1px;
        }

        .info-box-content {
            font-size: 0.9em;
            color: #1e3a8a;
            line-height: 1.6;
        }

        /* ============================================
           BACK TO TOP LINK
           ============================================ */
        .back-to-top {
            display: inline-block;
            margin-top: 20px;
            color: #3b82f6;
            font-weight: 700;
            text-decoration: none;
            font-size: 0.9em;
            padding: 8px 16px;
            border-radius: 6px;
            background: linear-gradient(145deg, #dbeafe 0%, #bfdbfe 100%);
            border: 1px solid #93c5fd;
            box-shadow: 0 2px 4px rgba(59, 130, 246, 0.2);
            transition: all 0.3s ease;
        }

        .back-to-top:hover {
            background: linear-gradient(145deg, #bfdbfe 0%, #93c5fd 100%);
            transform: translateY(-2px);
            box-shadow: 0 4px 8px rgba(59, 130, 246, 0.3);
        }

        /* ============================================
           RESPONSIVE
           ============================================ */
        @media (max-width: 768px) {
            body {
                padding: 20px 10px;
            }

            .header {
                padding: 20px 20px;
            }

            .header-title {
                font-size: 1.5em;
            }

            .header-subtitle {
                font-size: 0.9em;
            }

            .section-title {
                font-size: 1em;
            }

            .section-inner {
                padding: 20px;
            }

            table {
                font-size: 0.85em;
            }

            th, td {
                padding: 8px 10px;
            }

            .nav-container {
                gap: 8px;
            }

            .nav-button {
                padding: 8px 12px;
                font-size: 0.7em;
            }

            .site-cards-grid {
                grid-template-columns: 1fr !important;
            }

            .priority-text {
                font-size: 1.3em;
            }
        }

        /* ============================================
           PRINT STYLES
           ============================================ */
        @media print {
            body {
                background: white;
                padding: 0;
            }

            .nav-container,
            .priority-title-container,
            .site-cards-grid,
            .table-controls,
            .export-btn,
            .back-to-top {
                display: none !important;
            }

            .section,
            .site-subsection {
                page-break-inside: avoid;
                box-shadow: none;
                border: 1px solid #ddd;
            }

            .section-content,
            .subsection-content {
                max-height: none !important;
            }

            table {
                page-break-inside: auto;
            }

            tr {
                page-break-inside: avoid;
                page-break-after: auto;
            }

            thead {
                display: table-header-group;
            }
        }
    </style>
    """


# =============================
# 🔧 JAVASCRIPT FUNCTIONS
# =============================

def get_javascript() -> str:
    """JavaScript for interactive features."""
    return """
    <script>
        // Toggle main sections
        function toggleSection(sectionId) {
            const section = document.getElementById(sectionId);
            if (section) {
                section.classList.toggle('expanded');
            }
        }

        // Toggle site subsections
        function toggleSubsection(siteId) {
            const subsection = document.getElementById('subsection-' + siteId);
            if (subsection) {
                subsection.classList.toggle('expanded');
            }
        }

        // Expand section programmatically
        function expandSection(sectionId) {
            const section = document.getElementById(sectionId);
            if (section && !section.classList.contains('expanded')) {
                section.classList.add('expanded');
            }
        }

        // Scroll to element with offset
        function scrollToSection(elementId, offset = 80) {
            const element = document.getElementById(elementId);
            if (element) {
                const elementPosition = element.getBoundingClientRect().top;
                const offsetPosition = elementPosition + window.pageYOffset - offset;

                window.scrollTo({
                    top: offsetPosition,
                    behavior: 'smooth'
                });
            }
        }

        // Navigate to section and expand
        function navigateToSection(sectionId) {
            expandSection(sectionId);
            setTimeout(() => {
                scrollToSection(sectionId);
            }, 100);
        }

        // Navigate to site detail
        function navigateToSite(siteId) {
            expandSection('section-site-details');
            const subsectionId = 'subsection-' + siteId;
            setTimeout(() => {
                expandSection(subsectionId);
                scrollToSection(subsectionId);
            }, 300);
        }

        // Sort table by column
        function sortTable(tableId, columnIndex) {
            const table = document.getElementById(tableId);
            if (!table) return;

            const tbody = table.getElementsByTagName('tbody')[0];
            const rows = Array.from(tbody.getElementsByTagName('tr'));

            const currentDirection = table.getAttribute('data-sort-direction') || 'asc';
            const newDirection = currentDirection === 'asc' ? 'desc' : 'asc';
            table.setAttribute('data-sort-direction', newDirection);

            rows.sort((a, b) => {
                const aCell = a.getElementsByTagName('td')[columnIndex];
                const bCell = b.getElementsByTagName('td')[columnIndex];

                if (!aCell || !bCell) return 0;

                let aValue = aCell.textContent.trim();
                let bValue = bCell.textContent.trim();

                const aNum = parseFloat(aValue.replace(/[^0-9.-]/g, ''));
                const bNum = parseFloat(bValue.replace(/[^0-9.-]/g, ''));

                if (!isNaN(aNum) && !isNaN(bNum)) {
                    return newDirection === 'asc' ? aNum - bNum : bNum - aNum;
                }

                return newDirection === 'asc' 
                    ? aValue.localeCompare(bValue) 
                    : bValue.localeCompare(aValue);
            });

            rows.forEach(row => tbody.appendChild(row));
        }

        // Filter table rows
        function filterTable(tableId, searchBoxId) {
            const input = document.getElementById(searchBoxId);
            const filter = input.value.toUpperCase();
            const table = document.getElementById(tableId);

            if (!table) return;

            const tbody = table.getElementsByTagName('tbody')[0];
            const rows = tbody.getElementsByTagName('tr');

            for (let i = 0; i < rows.length; i++) {
                const cells = rows[i].getElementsByTagName('td');
                let found = false;

                for (let j = 0; j < cells.length; j++) {
                    const cellText = cells[j].textContent || cells[j].innerText;
                    if (cellText.toUpperCase().indexOf(filter) > -1) {
                        found = true;
                        break;
                    }
                }

                rows[i].style.display = found ? '' : 'none';
            }
        }

        // Export table to CSV
        function exportTableToCSV(tableId, filename) {
            const table = document.getElementById(tableId);
            if (!table) return;

            let csv = [];
            const rows = table.querySelectorAll('tr');

            for (let row of rows) {
                let rowData = [];
                const cells = row.querySelectorAll('th, td');

                for (let cell of cells) {
                    let text = cell.textContent.trim();
                    text = text.replace(/"/g, '""');
                    if (text.includes(',')) {
                        text = '"' + text + '"';
                    }
                    rowData.push(text);
                }

                csv.push(rowData.join(','));
            }

            const csvContent = csv.join('\\n');
            const blob = new Blob([csvContent], { type: 'text/csv' });
            const url = window.URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.setAttribute('href', url);
            a.setAttribute('download', filename);
            a.click();
        }

        document.addEventListener('DOMContentLoaded', function() {
            const paretoSection = document.getElementById('section-pareto-matrix');
            if (paretoSection) {
                paretoSection.classList.add('expanded');
            }
        });
    </script>
    """


# =============================
# 🧱 HTML COMPONENT BUILDERS
# =============================

def build_header(customer_name: str, week_start: str, week_end: str, scope_type: str, timestamp: str) -> str:
    """Build report header in chrome / Waymo style."""
    return f"""
    <div class="header">
        <div class="header-title">🛡️ Excellence Performance Center 🛡️</div>
        <div class="header-subtitle" style="font-size: 1.2em; margin-bottom: 6px;">
            SCHEDULE OPTIMIZATION REPORT
        </div>
        <div class="header-meta-line">
            <strong>Customer:</strong> {customer_name} <span style="color: #3b82f6;">|</span> <strong>Week:</strong> {week_start} – {week_end} <span style="color: #3b82f6;">|</span> <strong>Scope:</strong> {scope_type}
        </div>
        <div class="header-meta-line">
            <strong>Report Generated:</strong> {timestamp}
        </div>
    </div>
    """


def build_metadata_cards(cards: List[Dict[str, str]]) -> str:
    """Build metadata cards grid (Waymo-style meta panel)."""
    cards_html = ""
    for card in cards:
        # Get conditional class if specified
        card_class = card.get('class', '')
        class_attr = f' class="metadata-card {card_class}"' if card_class else ' class="metadata-card"'
        
        cards_html += f"""
        <div{class_attr}>
            <div class="metadata-label">{card['label']}</div>
            <div class="metadata-value">{card['value']}</div>
        </div>
        """
    
    return f"""
    <div class="metadata-grid">
        {cards_html}
    </div>
    """


def build_navigation_buttons(sections: List[Dict[str, str]]) -> str:
    """Build navigation button row (chrome buttons)."""
    buttons_html = ""
    for section in sections:
        buttons_html += f"""
        <button class="nav-button" onclick="navigateToSection('{section['id']}')">
            {section['label']}
        </button>
        """
    
    return f"""
    <div class="nav-container">
        {buttons_html}
    </div>
    """


def build_status_badge(nbot_status: str) -> str:
    """Build status badge."""
    badge_class = {
        'RED': 'badge-red',
        'YELLOW': 'badge-yellow',
        'GREEN': 'badge-green'
    }.get(nbot_status, 'badge-blue')
    
    return f'<span class="status-badge {badge_class}">{nbot_status}</span>'


def build_info_box(title: str, content: str, box_type: str = 'default') -> str:
    """Build info box (mapped to Waymo-style info panel)."""
    type_map = {
        'default': '',
        'warning': 'border-left-color: #f59e0b; background: linear-gradient(145deg, #fef3c7 0%, #fde68a 100%);',
        'critical': 'border-left-color: #dc2626; background: linear-gradient(145deg, #fee2e2 0%, #fecaca 100%);',
        'success': 'border-left-color: #059669; background: linear-gradient(145deg, #dcfce7 0%, #bbf7d0 100%);',
        'info': 'border-left-color: #3b82f6;'
    }
    style = type_map.get(box_type, '')
    return f"""
    <div class="info-box" style="{style}">
        <div class="info-box-title">📋 {title}</div>
        <div class="info-box-content">{content}</div>
    </div>
    """


def build_table_with_controls(
    table_id: str,
    search_box_id: str,
    headers: List[str],
    rows: List[List[str]],
    export_filename: str
) -> str:
    """Build table with search and export controls using chrome theme."""
    headers_html = ""
    for idx, header in enumerate(headers):
        headers_html += f'<th onclick="sortTable(\'{table_id}\', {idx})">{header}</th>'
    
    rows_html = ""
    for row in rows:
        rows_html += "<tr>"
        for cell in row:
            rows_html += f"<td>{cell}</td>"
        rows_html += "</tr>"
    
    return f"""
    <div class="table-container">
        <div class="table-controls">
            <input type="text" 
                   id="{search_box_id}" 
                   class="search-box" 
                   placeholder="🔍 Search table..." 
                   onkeyup="filterTable('{table_id}', '{search_box_id}')">
            <button class="export-btn" onclick="exportTableToCSV('{table_id}', '{export_filename}')">
                📥 Export to CSV
            </button>
        </div>
        <table id="{table_id}">
            <thead>
                <tr>{headers_html}</tr>
            </thead>
            <tbody>
                {rows_html}
            </tbody>
        </table>
    </div>
    """
