"""Export tool for root orchestrator to save reports as HTML/PDF."""

import os
from typing import Literal, Optional
from ..utils.export_utils import export_report, get_cst_timestamp


def export_agent_report(
    report_content: str,
    format: Literal['html', 'pdf'] = 'html',
    report_type: str = 'agent_report',
    agent_name: Optional[str] = None,
    output_dir: str = './reports'
) -> str:
    """
    Export a report from a sub-agent to HTML or PDF format.
    
    This tool allows Jordan to save reports generated by sub-agents
    (Nick, Sammy, Joe, Elena, Zuri, Amanda) to file for Carlos.
    
    Args:
        report_content: The markdown/text content of the report to export
        format: Output format - 'html' or 'pdf' (default: 'html')
        report_type: Type of report (e.g., 'nbot_analysis', 'schedule_optimization', 'training_compliance')
        agent_name: Name of the agent that generated the report (e.g., 'Nick', 'Sammy')
        output_dir: Directory to save the report (default: './reports')
    
    Returns:
        Success message with file path, or error message
    
    Example:
        export_agent_report(
            report_content=nbot_report,
            format='pdf',
            report_type='nbot_weekly_summary',
            agent_name='Nick'
        )
    """
    try:
        # Create output directory if needed
        os.makedirs(output_dir, exist_ok=True)
        
        # Generate descriptive filename
        timestamp = get_cst_timestamp("%Y-%m-%d_%H-%M-%S")
        
        # Build filename components
        parts = ['epc']
        if agent_name:
            parts.append(agent_name.lower())
        parts.append(report_type.lower().replace(' ', '_'))
        parts.append(timestamp)
        
        filename = '_'.join(parts)
        
        # Export the report
        file_path = export_report(
            markdown_content=report_content,
            format=format,
            output_dir=output_dir,
            filename=filename
        )
        
        # Return success message
        return f"""
✅ **Report exported successfully!**

📁 **File Location:** `{file_path}`
📊 **Report Type:** {report_type}
👤 **Generated By:** {agent_name or 'EPC Agent'}
📄 **Format:** {format.upper()}
🕐 **Timestamp:** {timestamp}

**Next Steps:**
- Open the file to review the complete report
- Share with stakeholders as needed
- Archive for future reference

💡 **Pro Tip:** PDF format is best for sharing, HTML format preserves interactivity.
"""
    
    except Exception as e:
        return f"""
❌ **Export failed!**

**Error:** {str(e)}

**Troubleshooting:**
- Verify report content is valid markdown
- Check output directory permissions
- Ensure format is 'html' or 'pdf'

Please try again or contact support if the issue persists.
"""